### ISSUE TITLE
1.0.3 installer installs 1.0.1 dlls

### ISSUE THREAD

**Issue by SID800** [Dionach/StripHeaders#1]
The installer (iis_stripheaders_module_1.0.3.msi) installs dlls which have a version of 1.0.1.  Windows 2012 R2. 

programs & features:
![image](https://cloud.githubusercontent.com/assets/12401288/7575168/a7f71c7e-f7e7-11e4-80f5-e711e14cccd7.png)

Yet the dll version states its 1.0.1
![image](https://cloud.githubusercontent.com/assets/12401288/7575187/d0459f84-f7e7-11e4-9040-bcf594609069.png)

**Comment by ph1ll** [comment]
Thank you for the report, I believe whilst the dll version was not updated, it was in fact the version from 1.0.3, however this is fixed in 1.0.4 so that both the installer version and the dll version are the same
