### ISSUE TITLE
w3wp crash on app pool cycle from invalid reference

### ISSUE THREAD

**Issue by SID800** [Dionach/StripHeaders#2]
Windows 2012 R2.  
Either on automatic or manual app pool cycle, this causes the W3WP process to crash.    Stack trace:

```
0:000> knL
  *** Stack trace for last set context - .thread/.cxr resets it
# Child-SP          RetAddr           Call Site
00 0000009f`6cd6fa28 00007ff9`713bb7cb 0x0
01 0000009f`6cd6fa30 00007ff9`72ad4e34 nativerd!TerminateNativeConfiguration+0x2b
02 0000009f`6cd6fa60 00007ff9`72ad4934 w3wphost!W3WP_HOST::~W3WP_HOST+0x1d4
03 0000009f`6cd6fa90 00007ff7`275320ca w3wphost!AppHostInitialize+0x200
04 0000009f`6cd6fad0 00007ff7`2753392d w3wp!wmain+0x40e
05 0000009f`6cd6fc70 00007ff9`795513d2 w3wp!__wmainCRTStartup+0x13d
06 0000009f`6cd6fcb0 00007ff9`7991e954 kernel32!BaseThreadInitThunk+0x22
07 0000009f`6cd6fce0 00000000`00000000 ntdll!RtlUserThreadStart+0x34
```

Initial analysis from Microsoft was the release of _nativerd!CONFIG_SYSTEM in TerminateNativeConfiguration is causing a stack buffer overrun_.   More detailed analysis by a MS developer as as follows, which includes hints on how to fix the code.

> The reference count on the CONFIG_SYSTEM object is already down by 1 by the time the idna was started.
> 
> However after examining the code and the data in the dump and idna trace, it appears that the stripheaders module is to blame. In its RegisterModule function it calls GetAdminManager from the IHttpServer pointer that IIS passes to it. GetAdminManager returns an IAppHostAdminManager pointer, which is just one of the interfaces on the INativeConfigurationSystem object, which is the main interface of the nativerd!CONFIG_SYSTEM class. With this pointer it makes two interface calls. The first is GetConfigSection (which makes sense. It wants to read some startup config info.), then near the end of the function it makes the second call, which is the Release(). You should NOT call release on any interface you get from IHttpServer, IHttpContext, or any of these interfaces, unless YOU have specifically called AddRef. IIS does not take an extra reference for you, and in any cases that it does it calls Release itself, or documents very clearly that you must call Release(). That is not he case for the IHttpServer instance that is passed into to RegisterModule (stripheaders does not call Release on this) and it is not the case for the IAppHostAdminManager instance obtained from IHttpServer::GetAdminManager. In both cases there is NO extra ref taken, and you MUST NOT call Release without first calling AddRef.
> 
> If fixing the bug in this module, or removing the module, does not completely resolve the issue (it seems that it would, since according to the debug the reference count was off by only one), then the following troubleshooting steps can be taken: 
> 
> It is possible to use the checked build of nativerd to get reference callstacks. Or I could build a retail one with it enabled. A dump of the crash will contain the reference trace in memory and dtext can be used to dump it out.
> 
> We can look for callers of GetDefaultNativeConfigurationSystem(), and then see who is dereferencing too many times. This can be done by getting a 'working' dump before recycling and examining the imports/calls by the various modules loaded.
> 
> As mentioned above for stripheaders.dll, there is the possibility that another httpmodule or handler has obtained a pointer to the config from w3server (like from the http context or RegisterModule/Handler) and has released it too much (or at all). Again in the case of RegisterModule you should NOT call Release on the IHttpServer passed in or any interface instance you obtain from one of its members, unless you have first called AddRef on it. IIS does NOT take an extra ref before handing it to modules.

**Comment by ph1ll** [comment]
Thank you for the very detailed report, and please thank the MS developer for taking the time to do the detailed debugging and providing so much information. Version 1.0.4 is now available on the releases page and removes the incorrect call to release. I believe this was left in following some performance improvements. 

Please let me know if you have any issues with the updated version.

**Comment by SID800** [comment]
thanks for the quick release.  I can confirm the issue has been resolved.

**Comment by smaglio81** [comment]
I noticed on https://www.dionach.com/blog/easily-remove-unwanted-http-headers-in-iis-70-to-85, that the download link within the Installation section is to version 1.0.3. Should that link be updated to 1.0.4?

**Comment by mrchief** [comment]
> Should that link be updated to 1.0.4?

Definitely! Or better, just point it to github releases page. That way, users can grab whatever the latest is.

I was facing the same w3wp crash issue when I spotted this last comment. Incidentally, as the 1.0.4 msi was uninstalling 1.0.3, it crashed few times! :)

**Comment by ph1ll** [comment]
Links on the blog have been updated

**Comment by mrchief** [comment]
:+1:
