### ISSUE TITLE
windows 10 support?

### ISSUE THREAD

**Issue by elibyy** [Dionach/StripHeaders#3]
hey there, i can't seem to be able to install this module on windows 10 i get only iis 7 and above is supported

**Comment by ph1ll** [comment]
Hi, there has been no testing for Windows 10, in fact all testing has been for Windows Server. The installer performs a simple version check of `%windir%\system32\inetsrv\w3wp.exe`, ensuring it is above `7.0`.

Could you check the version of `w3wp.exe` on your system and let me know what the version number is? I am assuming it will be `10.x.x.x`, but it may provide an indication of why the installer is not detecting it.

**Comment by elibyy** [comment]
i've occured to the same error with [phpmanager](https://phpmanager.codeplex.com/workitem/2653) because the version is stored as hex in the registry so the value is a=10 and the w3wp.exe version is 10.0.10240.16384

**Comment by smaglio81** [comment]
Thanks for creating this module. I tried to use a Windows Server 2016 Technical Preview 4 to try the installer. It's also reporting the version error:

![image](https://cloud.githubusercontent.com/assets/169953/12935211/0ff43206-cf49-11e5-9e31-36d08629a0cf.png)

The version information out of PowerShell looks to be 10.0.10586.0 (maybe?).

> PS C:\Users\smaglio> Get-ItemProperty C:\Windows\system32\inetsrv\w3wp.exe | fl *
> 
> PSPath            : Microsoft.PowerShell.Core\FileSystem::C:\Windows\system32\inetsrv\w3wp.exe
> PSParentPath      : Microsoft.PowerShell.Core\FileSystem::C:\Windows\system32\inetsrv
> PSChildName       : w3wp.exe
> PSDrive           : C
> PSProvider        : Microsoft.PowerShell.Core\FileSystem
> Mode              : -a---l
> VersionInfo       : File:             C:\Windows\system32\inetsrv\w3wp.exe
>                     InternalName:     w3wp.exe
>                     OriginalFilename: w3wp.exe.mui
>                     FileVersion:      10.0.10586.0 (th2_release.151029-1700)
>                     FileDescription:  IIS Worker Process
>                     Product:          Internet Information Services
>                     ProductVersion:   10.0.10586.0
>                     Debug:            False
>                     Patched:          False
>                     PreRelease:       False
>                     PrivateBuild:     False
>                     SpecialBuild:     False
>                     Language:         Language Neutral
> 
> BaseName          : w3wp
> Target            : {C:\Windows\WinSxS\amd64_microsoft-windows-processmodel-cpt_31bf3856ad364e35_10.0.10586.0_none_375
>                     822d41de7fa67\w3wp.exe}
> LinkType          : HardLink
> Name              : w3wp.exe
> Length            : 24576
> DirectoryName     : C:\Windows\system32\inetsrv
> Directory         : C:\Windows\system32\inetsrv
> IsReadOnly        : False
> Exists            : True
> FullName          : C:\Windows\system32\inetsrv\w3wp.exe
> Extension         : .exe
> CreationTime      : 10/30/2015 8:19:12 AM
> CreationTimeUtc   : 10/30/2015 8:19:12 AM
> LastAccessTime    : 2/9/2016 11:49:06 PM
> LastAccessTimeUtc : 2/9/2016 11:49:06 PM
> LastWriteTime     : 2/9/2016 11:49:06 PM
> LastWriteTimeUtc  : 2/9/2016 11:49:06 PM
> Attributes        : Archive

**Comment by smaglio81** [comment]
I was able to hand install all the components on the Win2016 TP4 and the module worked great!

So, I started to search around on how to update the installer. I found [this article](https://lostechies.com/gabrielschenker/2009/06/26/walking-through-the-creation-of-a-complex-installer-package/), which shows that a `RegistrySearch` can be done to find the `IISInstalledMajorVersion`.

I guess that's what the Application Initialization team did to [overcome the same problem](http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_web/new-iis-version-in-windows-10-build-10041-not/a68128e2-3a35-4c3a-9994-47bceafa7d0f?auth=1).

I think you could use a conditional statement like this to check for all the versions (currently available).

> <![CDATA[Installed OR (IISInstalledMajorVersion>= "#7" OR IISInstalledMajorVersion= "#10")]]>

My apologizes for not creating a pull request for the update. But, I wasn't able to validate that the updated check would work. I've never built a WiX projects before and I'm unable to get the installer to properly compile.

PS. @elibyy - I tried to write a PowerShell script to download, extract and install all the pieces. But, I couldn't get msiexec to unpack both the x86 and x64 versions from the msi. If you know the command line to get both versions to unpack, I can finish up the script. (I was using `msiexec /a iis_stripheaders_module_1.0.4.msi /qb TARGETDIR=C:\temp`)

**Comment by jamsoft** [comment]
Just to let you guys know I've started to update the installer in my fork.  Although I'm still working on one little annoying issue.

There are a number of other issues in the original installer that are not following recommended Windows Installer best practice, so I'm also fixing those issues at the same time.  But time is short and WiX is a particularly obfuscated and temperamental tech.

**Comment by scomnoob** [comment]
project is live? i see lot of pull requests..

**Comment by RvdHout** [comment]
Bump, any progress on the installer to support Windows 10 / Server 2016?

**Comment by ph1ll** [comment]
Apologies for the delay in getting to this. I meant to have it sorted prior to Server 2016 release. It seems the problem with the version check is that the MSI performs a string comparison rather than a proper version comparison. 

For now, I will remove the version check, as hopefully no one is trying to use it on IIS 6 anyway.

**Comment by elibyy** [comment]
thanks
