### ISSUE TITLE
HEAD/Content-Length

### ISSUE THREAD

**Issue by ecc256** [Dionach/StripHeaders#4]
Need to remove _Content-Length_ for **HEAD** verb.
Looks like no easy way to remove headers like _Content-Length_ or _Date_?

**Comment by ph1ll** [comment]
Removing a header for a particular verb is outside the scope of this module. However it would be fairly straight forward to fork and add a check for the verb. 

Content-Length and Date headers are set by IIS at some point near the end of the pipeline,  after any modules have executed, as obviously modules could change the values of these. It is therefore not possible to remove then in IIS, and as the are required by the HTTP spec, doing so is generally a bad idea.

**Comment by ecc256** [comment]
Phill,
Per rfc7231 [payload header](https://tools.ietf.org/html/rfc7231#section-3.3) may MAY be omitted for [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2)

The reason is we have relatively heavy back end processing, so we do bypass it for HEAD and send empty body right away. However, IIS adds _Content-Length=0_ for such response.

I hoped your StripHeaders can be used to remove wrong header. It’s easy to adapt it for HEAD processing.

And you are right, Content-Length header is not even set when StripHeaders module is fired.
And it looks like module priority is set so it is executed last for **RQ_SEND_RESPONSE** notification.

Could you suggest another approach to handle it, please?
I’m out of ideas...

**Comment by ph1ll** [comment]
I'm afraid there isn't anything I am aware of, but then the native code module documentation on MSDN isn't great. If possible, it may be worth reaching out to MS support. 

The only solution I can think of is to have a reverse proxy in front of IIS that handles HEAD requests directly and passes remaining requests to IIS. I'm not sure of your exact requirements, but this seems like an odd setup.

Is there a reason why Content-Length=0 is not acceptable? If you are already skipping the heavy backend, I am guessing this is causing some issue with your client?

**Comment by ecc256** [comment]
Phill,
MS support is pretty much useless, IMO.
It takes forever to get escalated to somebody knowledgeable enough to be able to help.
"Been there, seen that" quite few times already.

Proxy won’t help with https.

It looks like Content-Length=0 doesn’t work, because [some?] search engines are smart enough to deduce, there is nothing to index there. They won’t do GET, if HEAD returned Content-Length=0.

**Comment by ph1ll** [comment]
If it's a case of tricking search engines, could you do something like instead of faking an empty body, include some static content, so that when IIS sends the HEAD response the content length is > 0?

**Comment by ecc256** [comment]
I can set Content-Length to some reasonable value (which vary a lot between different pages and not that much for same page for different requests). But I have a feeling this approach will blow sooner or later.

Problems with SE do not manifest themselves right away.
And when they are detected, it’s usually too late.

I guess, we are quite off topic already.
Thanks for trying to help anyway!
